### ISSUE TITLE
Trajectory ground truh 

### ISSUE THREAD

**Issue by yhabib29** [Hilti-Research/hilti-slam-challenge-2023#10]
Hi,
Do you plan on releasing the ground truth trajectories?
I'm not sure if an announcement has been made regarding this.

Thank you 😄

**Comment by hilti-challenge** [comment]
Hi @yhabib29 
Thanks for reaching out!

We do not plan to do so just yet. 
But we are maintaining a list of all feature requests and shall schedule updates accordingly.

Best,
The Hilti SLAM Challenge Team
