### ISSUE TITLE
Coordinates for robot-mounted sensor suite

### ISSUE THREAD

**Issue by LarryDong** [Hilti-Research/hilti-slam-challenge-2023#11]
Hi,

Thanks for releasing the dataset. 
We're using the dataset but confused about the coordinate of different cameras, IMU, and Lidar.

We could only find the calibrated yaml from the webpage, but we need a figure to show where are those sensor mounted and corresponding coordinate.
Please provide a reference figure if convenient. 

Thanks.

**Comment by jukindle** [comment]
Hi Larry,

Could you describe a little further? [In the documentation](https://github.com/Hilti-Research/hilti-slam-challenge-2023/blob/main/documentation/hardware/Robot.md#system-overview), there are multiple images with the corresponding coordinate systems available.

**Comment by LarryDong** [comment]
Hi, thanks for this documentation. I'm sorry that we didn't find it.
