### ISSUE TITLE
Automatic Evaluation system not working yet?

### ISSUE THREAD

**Issue by dongjae0107** [Hilti-Research/hilti-slam-challenge-2023#3]
Hi. Thank you for organizing the great challenge and releasing the dataset.

Actually, We submitted our results to check accuracy of our method, but we are consistently getting zero score. We have carefully reviewed our results and confirmed that they meet the form requirements. Furthermore, we are particularly surprised that we received a zero score even for measurements greater than 10cm.

Is the scoring system not working yet? If it doesn't work, when will it work?

Best Regards

**Comment by hilti-challenge** [comment]
Hi @dongjae0107 ,
Thanks for your message! We noticed an invalid quaternion in your submission in the first line.

1674573641.2034380436 0.0 0.0 0.0 0.0 0.0 0.0 0.0

If you correct this you get a valid score.
That said, we are working towards providing better automated feedback to contestants.

Best,
The Hilti SLAM Challenge Team
