### ISSUE TITLE
Question for Hilti-challenge-2023 leaderboard

### ISSUE THREAD

**Issue by jungyun0609** [Hilti-Research/hilti-slam-challenge-2023#4]
Dear Hilti-Challenge-2023 Organizers,

I am a student who is currently showing great interest in participating in the Hilti-Challenge-2023. I have a query that I wish to address through this GitHub issue. Upon reviewing the events of the previous years, I noticed that the challenge leaderboards were made accessible to the public.

In light of this, I would be grateful if you could provide me with some information regarding the anticipated opening date for this year's leaderboard. I would like to express my utmost gratitude for your efforts in sharing the data publicly, which greatly benefits the community.

Thank you for your attention, and I look forward to your response.

Sincerely, 
jungyun Kim

**Comment by hilti-challenge** [comment]
Hi Jungyun Kim (@jungyun0609)!

Thanks for reaching out.

We make the live leaderboard publicly accessible only after the results are announced at the Future of Construction Workshop at ICRA 2023 (same as the previous years challenge). The date for that would be June 2nd 2023, so you can expect the leaderboard to be live by **June 3rd, 2023**.

Furthermore, as mentioned in the FAQ section, after the deadline is passed we inform all contestants of their leaderboard position. This is based on their best submission score.

Hope this helps :)

Best regards,
The Hilti SLAM Challenge Team
