### ISSUE TITLE
Evaluation system changes

### ISSUE THREAD

**Issue by RumblingTurtle** [Hilti-Research/hilti-slam-challenge-2023#5]
Hi! About an hour ago all submissions were invalidated. Can you elaborate on how the overall score is calculated?

**Comment by hilti-challenge** [comment]
A quick update @RumblingTurtle :
The scores are now visible, reflecting the updated scoring system. 

However, you may notice that some pdf reports of submissions between April 18-19th do not match the updated scores.
This too shall be rectified.

Thank you for your understanding.

Best,
The Hilti SLAM Challenge Team

**Comment by plamenl** [comment]
Hello,
The score breakdown is as follows:
< 0.5cm -> 20 points
< 1cm → 10 points
< 3cm → 6 points
< 6cm → 5 points
< 10cm → 3 point
< 40cm -> 1 point
> 40cm → 0 points

Then the score for each trajectory is normalized to be in the 0-100 range.

Regarding the reference points, the number hasn't changed. If you don't have a part of your trajectory within a certain distance threshold to a control point, that control point would not be counted at all.

If you have questions for a particular submission, you can let us know the submission number and your submission team name, and we will look into it.

Best,
The Hilti SLAM Challenge Team

**Comment by RumblingTurtle** [comment]
@plamenl thanks! We found out that the error was on our side so no issues here
