### ISSUE TITLE
Are submissions closed prior to the deadline?

### ISSUE THREAD

**Issue by RumblingTurtle** [Hilti-Research/hilti-slam-challenge-2023#7]
![photo_2023-05-21_11-29-08](https://github.com/Hilti-Research/hilti-slam-challenge-2023/assets/10453957/d2d8bab1-e982-40be-98f3-0c07ba54c35b)

**Comment by maliksyria** [comment]
Yes, I'm really surprised about this too. It supposed to close at the end of this day!

**Comment by snakehaihai** [comment]
emm im surprised also... can organizer care to explain? @hilti-challenge

**Comment by jukindle** [comment]
@RumblingTurtle @maliksyria @snakehaihai seems as there was a mistake in the backend development, please keep submitting your results until 11.59pm, we'll clarify on Monday.

**Comment by hilti-challenge** [comment]
Hi all,
Thanks for reaching out. 

We will accept submissions till the end of the day.
Apologies for the confusion, this is a backend bug.
