### ISSUE TITLE
Has the leaderboard position been released to each team?

### ISSUE THREAD

**Issue by samsdolphin** [Hilti-Research/hilti-slam-challenge-2023#8]
Dear organizers, we have submitted our result before the deadline but we haven’t received any notification on our leaderboard position. May I know whether the leaderboard position has already been notified to each contest teams, or it remains to be released? Thanks!

**Comment by jaeseok4104** [comment]
arent you received mail? i think, winners already received email for result.

**Comment by samsdolphin** [comment]
> arent you received mail? i think, winners already received email for result.

sorry, i haven't received any email.

**Comment by jaeseok4104** [comment]
i think, other team is winners of this challenge. T_T

**Comment by GnssLab-ZZ** [comment]
> > arent you received mail? i think, winners already received email for result.
> 
> sorry, i haven't received any email.

Hello, I have the same question. Do you know anyone that has received the email?
![0BD74F61](https://github.com/Hilti-Research/hilti-slam-challenge-2023/assets/130761456/9d325cb1-5c85-4497-9d74-3be2f537694a)

**Comment by jukindle** [comment]
@samsdolphin @jaeseok4104 @GnssLab-ZZ Individual score emails will be sent later this week. The leaderboard will be made public on Monday.
